nodejs/package-maintenance

- README.md
Hi,
I have added to readme the slack information, referring to issue #118 
Hope this help
> docs: add slack channel info

- README.md
The `https` version of this url does not work, but the `http` version works.
> Update slack signup request url

- MEMBERS.md
Adding myself to the project. I am lead software engineer at [GoDaddy](https://github.com/godaddy) where we extensively use Node.js for building our platform and services. I'd love to contribute to maintaining Node.js and it's packages.
> feat(members): add Jacopo Daeli

- MEMBERS.md
As a long-time user and lover of Node.js since 2009-2010, the technology has a place close to my heart and has long been a crucial part in my various tech stacks. I myself have struggled under maintenance burdens for certain packages of my own authorship and believe that establishing a better baseline for stable and well-supported packages is crucial for the long-term success of the Node.js (and JavaScript, at large) ecosystem.
I am particularly interested in becoming a maintainer of the NeDB package as mentioned in https://github.com/nodejs/package-maintenance/issues/142#issuecomment-465694524, though would also be happy to help out when available with other packages, and certainly with providing some experienced opinions.
> Add @JamesMGreene as a member

- docs/drafts/versioning.md
Issue [158 versioning](https://github.com/nodejs/package-maintenance/issues/158) discourse has resulted in this brief advice for versioning. We are separating the versioning advice from the associated tooling that would or could enforce versioning.
> initial draft of versioning guidelines

- docs/drafts/licensing.md
In order to get the ball rolling with some actual prose. This may serve as a starting point. I'm not making any recommendations either for or against individual licenses. Rather I'm saying that we 
don't want
- restrictive
- patent
and do want
- the owner to have a license
- choose one appropriately 
I think it is not likely we actually would come across a project we want to support that has no license.
> add basic wording for licensing and open the debate up to PRs.

- docs/drafts/PUBLISH-GUIDELINES.md
Guideline for issue discussed https://github.com/nodejs/package-maintenance/issues/164
> doc: add draft publish guideline

- docs/drafts/testing-guidelines.md
Maybe changes:
Hello friends!
This is a first draft of testing guidelines. I started using the conversation in #157
> A first draft of testing guidelines

- pilots/SURVEY.md
Usually use a [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) to see if there are new versions in my package.json.  Unfortunately, it doesn't list `pre-release` or `next` versions which can [hide needed fixes](https://github.com/videojs/video.js/issues/5771).
Also, repos are scattered how they summarize changes.  Some do `CHANGELOG.md`, some write long descriptions in their release post, some just list the PR titles, & a few still use `README` or blogs.
> + Survey: version question

- docs/drafts/testing-guidelines.md
Closes #207 
I would like to add a link to #146 or we can build a menu in the README.md
> testing against LTS release and Current

- MEMBERS.md
I'm interested in becoming a member.  Similar to @lance, we are continuing to explore our "supporting" options for modules in the Node ecosystem here at Red Hat and i would like to lend any knowledge that i may have acquired with regards to that in the enterprise space
> Add @lholmquist as a member

- pilots/express/SURVEY_ANSWER.md
I know it has been slow in getting to these (which is why we need help), but here they are.  Let me know if there are any areas we can answer better.
> Express answers to survey

- MEMBERS.md
Adds @darcyclarke to MEMBERS.md
- ✅ Want to help make developer's lives easier
- ✅ Here as both an individual contributor but also as a conduit to/from the `npm` org
> Add @darcyclarke to memebers

- docs/drafts/PACKAGE-SUPPORT.md
I thought we talked about this at some point, but apparently it never made it into the draft.  Having a default expiration of 2 years seems like a reasonable default to prevent stale or incorrect data from sticking around for too long.
> (package-support) Set default support expiration to 2 years

- MEMBERS.md
Hi, 
I'm interested in becoming a member. We are continuing to explore our "supporting" options for modules in the Node ecosystem here at Red Hat also I'd like to get involved with [Express contributions triage efforts](https://github.com/expressjs/discussions/issues/92).
> Add @helio-frota as member

- MEMBERS.md
I came here per [this tweet](https://twitter.com/wesleytodd/status/1197270870269386752) from @wesleytodd and also [packagephobia#308](https://github.com/styfle/packagephobia/issues/308) @ghinks and @Eomm.
I can provide a TypeScript perspective of both a package author and package consumer. I also wrote [Package Phobia](http://packagephobia.now.sh) which is designed for package maintenance 😄
> Add styfle to MEMBERS.md

- docs/drafts/PACKAGE-SUPPORT.md
Fixes: https://github.com/nodejs/package-maintenance/issues/241#issuecomment-545178197
Update to add recommended integration with package.json
as outlined in: https://github.com/nodejs/package-maintenance/issues/241#issuecomment-545178197
> doc: update with recommended integration into package.json

- docs/drafts/security-guidelines.md
As a follow up to the discussion in #159 I put together a draft guidelines doc that I would love to have a discussion about.
The guidelines doc is mainly influenced by my experiences working with the Ecosystem Security WG.
> Security Reporting guidelines

- docs/drafts/PACKAGE-SUPPORT.md
Integrate the npm funding field into the
list of options for the backing field.
> doc: integrate npm funding into backing

- MEMBERS.md
I have not been actively participating in this working group since my day to day work has my focus shifted elsewhere. It seems best for me to remove myself from the list.
> doc: remove @lance from list of members

- MEMBERS.md
I've been involved in the Triage initiative in Express and find my OSS interests well aligned with this group's mission. 
I plan to continue to participate in the pilot efforts happening in Express, bring my feedback as a member of those efforts, and help to develop tools for package maintainers.
> Add @jonchurch as a member

- Charter.md
- Governance.md
- README.md
Initial version of docs for chartering
> Initial draft of docs for chartering

- docs/README.md
This small RP fixes link to testing guidelines in docs README
> doc: fix testing guidelines link

- README.md
resolves #372 
Adds an initial first draft of a space in the README to speak directly to maintainers, whom are a direct audience we want to make sure we communicate the outcomes of our work as a group to.  This is just to get something going, and that ideally it would grow as more resources and tools become available, like **wiby** or **status-dashboard**.
1. Is this heading ok?  Is its position in the README ok?
1. Anything else we should to the list of resources at this time?
> request for help / getting started documentation for package authors and maintainers

- Governance.md
After discussions with @dominykas et al during the package maintenance team meeting it was requested that a change was needed in our governance to handle the situation of PR being blocked when the reviewer had not responded for reasonable period of time.
The change being made is in no way an attempt to work around consensus but an attempt to handle cases of PRs being well reviewed by many participants but not being able to land due to the outstanding reviews that have in all likelihood been addressed.
> docs: PR landing, with outstanding reviews

- meetings/2020-09-08.md
> doc: add minutes for meeting 8 Sep 2020

- docs/PACKAGE-SUPPORT.md
Action point from #393 plus some other minor text/layout tweaks.
> Update package-support doc to include the latest release caveat

- Governance.md
As discussed in https://github.com/nodejs/package-maintenance/issues/410.
> feat: added publish guidelines for pkgjs owned packages

- docs/drafts/dependency-management-guidelines.md
Closes #280.
I feel this is too long, but right now I'm not sure what can I leave out... There's probably some stuff which should just point to some external content.
Anything that's worth expanding on? Did I miss anything important?
> Dependency management

- docs/drafts/security-guidelines.md
This reboots PR #315.
It differs so as to address @wesleytodd's concerns:
- Inlines URLs for consistency with the surrounding markdown.
- Replaces discussion of reputation systems with discussion of
defining bounds and adds an example of such a definition.
- Moves examples into existing table of example policy documents.
> security-guidelines: add advice on keeping vulns off public issue tracker

- docs/README.md
- docs/security-guidelines.md
Addresses #343 
There are several [HackerOne](https://hackerone.com/nodejs-ecosystem?type=team) links to a page that reads:
> The Node.js Ecosystem program is no longer accepting reports.
Please report any potential vulnerabilities to the respective Node.js Ecosystem disclosure channel.
This page will remain public as a thank you to the community for your contributions!
Not sure if all these links need to remain documented in this file.
> promote security-guidelines from draft

- docs/version-management/goals.md
A draft of the goals discussed in https://github.com/nodejs/package-maintenance/issues/595.
cc @nodejs/package-maintenance @nodejs/tsc
> Goals for Node.js and Package Manager Version Management Effort

- docs/version-management/proposal-revise-downloads-page.md
Following up #597, this is a proposal for a first step toward achieving those goals.
cc @nodejs/package-maintenance @nodejs/nodejs-website @nodejs/tsc
> doc: propose revising the downloads page

- docs/version-management/proposal-next-steps.md
A discussion was had in the OpenJS Slack about how to proceeded with next steps. This PR intends to represent what the folks in that thread think should be taken as next steps.
> feat: next steps for version management progress

- Governance.md
This group is not really active enough anymore to require 4 approvals — maybe it made sense back in 2020 when it was much more active, but not now :(
This hasn’t been previously discussed, so I understand if it gets blocked.
cc: @nodejs/package-maintenance
> update approval requirements for PRs in Governance.md
