README.md

oh hi! I'd love to get involved in this initiative. A bit about me:
* Cloud DevRel @ Google
* Node.js TSC
* Node.js release manager
* Heavily involved in LTS program
* Maintainer of a handful of packages
I'd love to help with making sure our Foundation has the appropriate
resources to support projects. I would also be interested in helping
to define LTS processes that can be adopted throughout the ecosystem

team: add Myles

---

README.md

I would like to offer my support and time in this initiative.

feat(members): add @ahmadnassri

---

README.md

Adding two more members I had talked to work
to gather support for initiative and who I
confirmed with today should be in the initial
team list.

doc: add additional members

---

README.md

I'd like to put some effort here, to help our great community become the greatest echo system.
I've contributed before with 2 merge requests in nodejs docs.
I also have some experience with working with open source projects such as loopback.

add Memeber

---

README.md

Hoping I can be a part of this to provide my experiences with my hundred+ npm packages to assist the facilitation of best practices.

readme: add @balupton

---

README.md

So Sorry.
somehow i did wrong about username
my is @wentout 
[request with mistake](https://github.com/nodejs/package-maintenance/pull/25)

add or delete @wentout

---

README.md

Hello, I am Larry, a Nodejs and Reactjs developer. I love javascript very much and I had a little experience contributing to open source project. I hope I can join and help this.

add a member

---

README.md

Big fan here of the Node and package ecosystem. 
Love to participate and would like to become a contributor to share skills.
Let me know how I can help.

add @ovhemert

---

README.md

Hi, I lead NodeJS app platform at WalmartLabs.
I am happy to help out with anything necessary to improve the NodeJS ecosystem, like documentation, review and testing packages, join meetings, or contribute code.
Thanks.

add @jchip

---

README.md

Hi,
I'm Kenigbolo Stephen, Full Stack Software Engineer and Arch Convener of Code Afrique. I'd be glad to contribute to package maintenance through documentation, testing, evangelising/advocating, and actual code contributions

add @kenigbolo

---

README.md

Hi!
I am currently working as tech lead for the Node.js Hosting in Acquia.
Since the time I started to work with Node.js, it's really exciting how the language evolved, how the community grew, it's amazing. So, I am excited to be a part of it, and help people to keep things up to date.
I am originally a Ruby developer, but looking forward to join the community.

Add Member Victor Alencar

---

README.md

I'm a web developer. Author of [WePY](https://github.com/Tencent/wepy). 
Currently I'm working in Tencent. I'd like to contribute any projects related to Node.js.
Help me to get on board. :0). Thanks.

Add Gcaufy

---

README.md

Hi!
I'm a web developer. Member of [WePY](https://github.com/Tencent/wepy).
I'd like to contribute to package-maintenance, and looking forward to join the community.
Thanks. :)

Add @dlhandsome

---

README.md

Hi. I'm so glad that found this great community.
Currently, I'm a frontend developer and also open-source project enthusiast (core team member of Nuxt.js and active contributor of Vue.js). I also have been keeping submitting commits to many open-source projects for more than 2 years.
I hope that I could get the opportunity to communicate with all great members here and solve problems together. I believe we can make the ecosystem better.

Add @clarkdo as a member

---

README.md

Hi there!
I would like to help the Node community do even better by improving and adding new changes to the documentation, as this is an important part of any such package.
I would also like to offer my various assistance in this initiative! :muscle:

Add @lex111 as member

---

README.md

Hi! As part of my work at Red Hat, I am beginning to explore our options for "supporting" (for some unspecified value of "supporting"), NPM ecosystem modules. Of course, as you know, enterprises are a little wary of just jumping in head first. I would like to help identify and support methods for improving the overall ecosystem, and perhaps automatically grading module quality.
We have already done some work around this effort by providing a license reporting tool that helps developers get a handle on the licenses included in all dependencies. https://github.com/nodeshift/license-reporter

doc: add @lance to team on README.md

---

README.md

Hello!
I have been working with Node.js for a long time. I am actually in charge of building https://github.com/usehenri/henri which is basically a framework aggregating the best packages to help developers build strong solutions. 
I have a first-hand knowledge of the troubles one might encounter by joining our community and selecting packages to render a viable solution.
I would be happy to join the discussion and help build a better ecosystem.

Add @reel as a member

---

README.md

Following on the [Call to Action](https://medium.com/@nodejs/call-to-action-accelerating-node-js-growth-e4862bee2919), I'd like to participate in this team.
My background:
I work for Slack as a leader on our developer tools. We publish several, [widely adopted node packages](https://github.com/slackapi) for usage of the Slack platform. It's critically important for our team to make it easy to adopt these packages in large enterprise companies, since the Slack Platform's value proposition depends on businesses building tools to improve the lives of their teammates.
Being a part of the Developer Relations team, I'm often in a position to hear how the current ecosystem and tools are not meeting the needs of these business customers. It's these experiences that have informed my views on what …

Add Ankur Oberoi as participant

---

README.md

I plan to contribute to helping with documentation and help with reviewing widely-used node package's code as per my capability and availability.
I'm full-time javascript developer and I feel this is an extraordinary step to make node ecosystem a better place.

Request for participation

---

README.md

Hello,
I have been working with node for a several years now and am interested in contributing regularly. As an engineer I bring a perspective matured by experience from working across different kinds of organizations at different stages and sizes. Currently I have active projects using node versions across 5, 6, 8, 9, 10 and 11, through nodejs, electron, and react-native/expo. I love the ecosystem and would love to assist in any way I can.
Thank you

adding Antonio Gonzalez

---

README.md

I am a student and code lover, I enjoy the ecosystem and would love to participate, it would be great if I can help in making it better.

add @esphas

---

README.md

If someone comes straight to this repo and needs more context, the article gives a good explanation.

Add Call to Action Article

---

README.md

Hello,
I have been working with node on a basic level since 2012, and am getting in to more serious projects with it now. As college faculty and past software developer, I am interested in the administration tasks as well as the fun coding parts. The recent breakdown in the event-stream package management likely spurred your new initiative, and I'd like to be a part of it, in part to keep me involved with node while I continue to develop a depth of knowledge in it.
Thank you for your consideration,
Amelia.

please add @argoc to nodejs package maint. team

---

README.md

Hello there,
I'm a UK based senior JavaScript programmer working full-stack.
I could relate to Michael Dawson's article strongly because, like many others, in my previous positions, such as Sky Sports, Cambridge University Press and others, I've built internal tools for Node.js dependency trees to  provide insight into complex applications in various forms (monorepo, microservice, monolith) which monitor and comply with regulations such as ISO27001, or, removing no longer maintained and insecure packages.
It would be great to work on tooling with like-minded people to give back to the community.
Thanks,
James

New team member

---

README.md

I wish to share my knowledge and to contribute code to some packages

Add myself as team member

---

README.md

I'm unfortunately not going to have the time to participate in this group.

doc: remove MylesBorins

---

README.md

Wanted to contribute by providing good documentation and resolving issues in the node ecosystem

Adding myself as team member

---

README.md

I'm a Node.js Developer with more than 4 years of experience in both backend and frontend technologies/frameworks.
I would like to dive deeper into Node.js, the technology that shaped my career, and become a contributor in this ecosystem. I will be happy to help out with anything I can.

Add @abdullahtariq91

---

README.md

I've been using node for ~6 years and have been making small contributions to various projects. I'm interested in improving the quality, security and longevity of packages in the ecosystem to make my clients and users happier, and hopefully my life as a developer easier and saner.
I'm happy to contribute docs, code or anything else that's needed, really.

Add @dominykas

---

README.md

I have been using node for 4+ years, both in backend and frontend. I am interested in start contributing, from documentation, fixes, or any task that help the community in any way i can

add @jmn8718

---

README.md

Hey! I saw the call to action on NodeWeekly. 
I've been using and building with Node for years now, and have been contributing to projects on Github. I've been wanting to get involved and help the core community, so this seems like a great place to start!
Thank you for considering me for the team.

Adding myself to the team

---

README.md

I'm an OSS maintainer and contributor. I've started contributing to Node recently and I think this initiative is somewhere I can help.

Adding myself to members list

---

README.md

I am the author of [Extended Memory Semantics](https://github.com/SyntheticSemantics/ems/) who recently left in limbo my five year old Node.js add-on despite two companies recently [opening an issue](https://github.com/SyntheticSemantics/ems/issues/20) and [filing a PR](https://github.com/SyntheticSemantics/ems/pull/24).
My background is in High Performance Computing and emerging architectures, I have presented EMS at [Node Summit 2017](https://vimeo.com/229686658) and other invited talks.

Add @mogill

---

README.md

I'm maintaining several small packages and try to contribute to OSS whenever possible. I'm much into CLI stuff with Node.js and always try to offer a great experience for possible package users.

add @lgraubner to team member list

---

README.md

Initially forgot to write. My primary focus will be on security on deprecated packages . Most of the organisation who are using nodejs have concerns over security . Would  contribute to make the nodejs ecosystem healthy :)

add @chandanrjit as a team member 

---

README.md

Hey,
I am working with node since 0.4 was out, I cannot remember how many packages I have been using so far but I know my basic set of libraries coming in to my projects again and again. Over the past 2 year I saw more and more often abandoned node/npm library projects or in need for help.
If we could find a way on how to help out, in terms of security fixes and keeping up with changes caused by node releases, it would be a great win for the whole npm/node eco-system.

add @chrkaatz

---

README.md

Hi there!
I would love to share my knowledge and to contribute code to these awesome packages.
I would also like to offer any other assistance in this initiative! 💪

Add myself as a team member

---

README.md

I've been using Node.js in production since 0.8.
I'm super interested in feeding back to the community and I held a Node Party in Shanghai, for native developers.
I think this project would make the Node's ecosystem better. I'd try to help the package migration to the newest Node.js version which I've done much in my own projects.

Add @aojiaotege to the list

---

README.md

I have been using Node.js for 5 years. I have always wanted to give back to the community through my open source contributions, and discovering this initiative was a very great motivation for me to start with contributing to the open source. 
My everyday job vary from these packages, and I see that some great packages lack on contributors so I would like to help in this case and start maintaining.

doc: add gentios as a team member

---

README.md

I am a Full Stack Javascript dev with rich experience on working with Node.js from the past 2 years. I have  been heavily using Node.js with something that deals with large amounts of data for Analytics purpose ensuring strict security checks. Also, I have been reporting vulnerabilities in npm packages as per the node advisories for some time now.
I would like to contribute to the node ecosystem and gain more in-depth knowledge along with giving back to the community as much as I can. Looking forward to be a part of this amazing team!

Add @kamesh95 as a team contributor

---

README.md

Hello, I'm Alessio from Italy. I would like to be added to this team 🤘

Add adnsio

---

README.md

Hi folks! Happy to see this effort taking shape.
I maintain a number of tools, services, and data modules designed to make it easier to understand the vast sea of npm modules. Namely:
- https://github.com/nice-registry/ghub.io
- https://github.com/nice-registry/all-the-package-names
- https://github.com/nice-registry/all-the-package-repos
I also maintain over 250 packages, and am always looking for new ways to make package maintenance more sustainable.
✅ I agree to uphold the Node.js Code of Conduct.

add @zeke to member list

---

README.md

Like to contribute where I deserve and have capability doing it. Either in defining/documenting process or developing tools to help solve challenges mentioned by @mhdawson. Or any other technical contribution asked for.

Please add me - like to contribute in my capacity and deservedness.

---

README.md

Hey there, I'm Hamza Baig. A full-stack developer in JS. I have been developing applications in NodeJS and JS related frontend libraries for more than 4 years now. Have been running and maintaining NodeJS in production.
I'd like to contribute to NodeJS ecosystem. I'll be more than happy to help with anything i can.

Add @hamxabaig

---

README.md

I'm Saif Jerbi, Senior frontend developer @Vermeg, i'm working with NodeJs for a while. I'm also a Developer advocate.
I'm looking to join the Project Team, i think i can help with writing articles about the ecosystem of nodeJS, Given feedbacks of the current ways we are using NodeJS in my Team(@work).

Join the team

---

README.md

I'd like to share my experience by assisting with documentation and addressing open issues for packages.

Join the team, fix an issue in the readme

---

README.md

Gonna fix issues and help another people to solve their issues.

Added myself in the team member list

---

MEMBERS.md

Hi there I'm the co-author of [MEVN-CLI](https://github.com/madlabsinc/mevn-cli) which is a tool intended for Developers built on top of Nodejs.
Docs available [here](https://mevn.madhacks.co)
> Looking forward to contribute further to the Node community.

Add myself to the members list

---

docs/README.md
docs/drafts/README.md

We need a place to start adding
documenting that we are working on within
the repository.

doc: add doc directory

---

MEMBERS.md

I would like to participate at the meetings.

doc: update members list

---

MEMBERS.md

I can help to upgrade packages dependencies, especially those involve security issues.

I would like to participate in the project

---

MEMBERS.md

How I plan to contribute to the teams effort.
By sharing my knowledge on package documentation, identifying priorities for packages on Node.js, and providing insights on community usage.

Add Hassan Sani as a member

---

MEMBERS.md

Like to be a member of package-maintenance so I can contribute by sharing my knowledge with other members.

I want to be one of maintainer

---

MEMBERS.md

I really want to help out by working with package maintainers to help keep packages stable and also help out in attending to issues. I will also love to share my knowledge with other members.

Add myself as a member

---

MEMBERS.md

I agree with the issues raised about old, widely used and unmaintained packages and the need for Node to ensure some security and support. I would like to contribute on issues and security maintenance of these packages and grow with the team and implement the effective solutions the community comes up with.

Wish to join the team

---

MEMBERS.md

I believe, success of many projects is a result of team work. Lets join and improve it.

Interested to join the team

---

MEMBERS.md

Hi all, Node is a crucial part in our tech stack, and I truly believe that having stable and well-supported packages is crucial for the entire ecosystem. We can hopefully contribute to issues, security and even refactoring and optimisation, and give back to the community.

Interested in joining the team

---

meetings/2019-02-11.md

minutes for 11 february

---

pilots/README.md
pilots/SURVEY.md

Hi,
based on the meeting of yesterday I send this PR for the issue #142 
The list is not completed, we are waiting for others feedback/comment/approvals, meanwhile, we could start with confirmed ones.
I was thinking if is it necessary to find out a "WG package-maintenance reference" per pilot package, not only for the module?

Pilot packages - cold start

---

MEMBERS.md

I'd like to help out! In particular around what tools we could develop/utilise to help module maintainers.

Add @BethGriggs as member

---

MEMBERS.md

I would love to participate in this working group on a personal level, but also as part of working at npm, which will give me the opportunity to use our internal expertise if/when needed.

add myself as a new member

---

MEMBERS.md

Unfortunately, I got laid off by npm, so I will need to focus on what…'s next for me before being involve here on a personal level (don't want to commit while not being sure anymore I can really help) #sadfred

Removing Frédéric Harper

---

pilots/survey-answers/mqttjs.md

As titled.
Let me know if you want me to change anything in the formatting.

Add MQTT.js responses.

---

README.md

'Goals' section now reads more clearly.

Update ReadMe - 'Goals'

---

meetings/2019-03-25.md

minutes meeting 2019-03-25

---

docs/drafts/tools.md

I would add this list in order to track the future tools that will be built.
If you think that is better to transfer the module from my profile to the Node.js, it is super ok 👍
Closes #161

add: tools.md

---

meetings/2019-06-17.md

Minutes 2019-06-17

---

MEMBERS.md

Working with Node.js & NPM daily would like to participate more actively in this group.
✔️ Would love to help with any maintenance work needed to be done.

Add @gntem to members.md

---

meetings/2019-10-08.md

Minutes 2019-10-08.md

---

docs/drafts/PUBLISH-BLOG.md

blog for https://github.com/nodejs/package-maintenance/issues/164

draft blog for publish baseline practices guide

---

docs/drafts/PACKAGE-SUPPORT.md

best-effort to time-permitting

---

meetings/2019-10-22.md

Sorry I was late to the PR for the meeting notes #272.  We also discussed the tooling org.

Added context for tool org usage

---

README.md

Pull Request Merging policy from issue [265](https://github.com/nodejs/package-maintenance/issues/265) describing the requirements for a PR to be merged.

PR  merge rules as discussed in team meeting.

---

MEMBERS.md

Inspired by @mhdawson 's CTA during his Node+JS Interactive talk and so wanted to offer myself as a contributor to the team / WG.
In particular, I have a lot of interests in release management / versioning, testing, and security but mostly I like to find ways to make and maintain processes and workflows that help people become more, and stay, productive within said process / workflows.
Also, really love JS / NodeJS and want to help support the community.  😊

add thescientist13 to members list

---

MEMBERS.md

Hi I would like to join the WG. 
So far I have been looking into ways to test a modules dependencies and opened this PR in Citgm https://github.com/nodejs/citgm/pull/765
Looking to get more involved in other areas

Add @andrewhughes101 as a member

---

MEMBERS.md

I've been working on packaging node modules for Debian for a while now and would like to be a part of this WG and volunteer to all the interesting stuff that goes on here with the sole purpose of helping with it in any way possible. I'm especially interested in [building packages](https://github.com/nodejs/package-maintenance/issues/67#issuecomment-578128104) that reflect this WG's description and ultimately help the community.

Add @rexagod to MEMBERS.md

---

meetings/2020-02-11.md

Fixes: https://github.com/nodejs/package-maintenance/issues/314
Please let me know if I missed you off the list (I copied the attendee list from the minutes) :pray:

doc: add minutes for 2020-02-11

---

meetings/2020-03-24.md

doc: add minutes for meeting 24 March 2020

---

docs/drafts/PACKAGE-SUPPORT.md

chore: fix formatting

---

EMERITUS.md
MEMBERS.md

I have not been able to fully contribute to this group, and that has been a failing on my end as my time commitments have been growing over the past year, I am unable to commit the time needed for weekly meetings and the tasks assigned.
I volunteer @darcyclarke as tribute 😉 he's already been contributing more than I ever could and I'm happy to see him as a member of this team going forward :)

move @ahmadnassri to emeritus status

---

docs/drafts/PACKAGE-SUPPORT.md

Fix a couple of minor typos in the draft.

Fix two spelling mistakes

---

meetings/2020-05-19.md

doc: add minutes for meeting 19 May 2020

---

meetings/2020-04-21.md

doc: add minutes for meeting April 21 2020

---

meetings/2020-04-07.md

doc: add minutes for meeting 7 April 2020

---

MEMBERS.md

Hello all!!
My name is Larson, I'm wanting to be a member so I can volunteer a lot of time to help out with all of the interesting stuff that is going on. I'm available to help in any way possible! All the way from documentation, community engagement, and package building. I'd also like to help give any input in any areas that I have experience in according to my GitHub profile.
Thank you all for your amazing work!

Add @larson-carter to Members.md

---

MEMBERS.md

Hi,
I'm currently maintaining [node-fetch](https://github.com/node-fetch/node-fetch) and some of my personal projects as well. I have a plenty of spare time, which I can spend helping with the issues :smile:
Thanks for your work!

Add Antoni Kepinski

---

meetings/2020-06-16.md

doc: add minutes for meeting 16 June 2020

---

MEMBERS.md

Hi,
I'd like to join community and ready to invest time in developing Node.js ecosystem.
Will be glad to reinforce your team and help with packages' issues\requests.

Add @rodion-arr to members

---

meetings/2020-07-14.md

doc: add minutes for meeting 14 July 2020

---

meetings/2020-06-02.md

doc: add minutes for meeting July 2

---

MEMBERS.md

Hi i'm Ash :wave: 
I work at IBM with @BethGriggs and @andrewhughes101 and plan to get involved with the tooling effort over in pkgjs

doc: Add AshCripps to members

---

MEMBERS.md

Hello I'm Ella 👋
I'm an intern working with @ghinks . This is my first time contributing to open source so I plan to start small by helping reading over docs =)

doc: add poloec1 to members

---

meetings/2020-07-28.md

doc: add minutes for meeting 28Jul 2020

---

ADMINISTRATIVE-MEMBERS.md
README.md

doc: propose initial set of administrative members

---

meetings/2020-08-25.md

doc: add minutes for meeting 25 Aug 2020

---

MEMBERS.md

Hello all!
I'm Sachin Jangid, I'm wanting to be a member so that I can reinforce the team and help with packages issues/requests. I can volunteer a lot of time to help out with all of the interesting stuff that is going on. I'd love to help in any way possible! All the way from documentation, community engagement to package building. Would love to invest time in developing Node.js ecosystem!
Thank you all for your amazing work!

Add @gittysachin as a member

---

meetings/2020-09-22.md

doc: add minutes for meeting 22 Sep

---

docs/README.md
docs/drafts/tools.md

As discussed in https://github.com/nodejs/package-maintenance/pull/300

fix: removed tools.md

---

meetings/2020-10-20.md

doc: add minuites for meeting 20 Oct

---

MEMBERS.md

i'm currently on the `modules-observers` team, but that effort is winding down. i'm looking to take the next step in contributing to nodejs, and improving package management seems like a potentially exciting avenue for that, as well a good way for me to apply what i've already learned & observed from the `modules` working group :smile:

add @zackschuster to members

---

meetings/2020-12-01.md

doc: add minutes for meeting 1 Dec 2020

---

meetings/2020-12-15.md

Signed-off-by: Michael Dawson <midawson@midawson.remote.csb>

doc: add minutes for meeting 15 dec 2020

---

meetings/2021-01-12.md

doc: add minutes for meeting Jan 12 2021

---

meetings/2021-02-09.md

doc: add minutes for 9 Feb 2021

---

meetings/2021-02-23.md

doc: add minutes for meeting 23 Feb

---

meetings/2021-04-06.md

doc: add minutes for meeting 6 April 2021

---

meetings/2021-04-22.md

doc: add minutes for meeting 22 April 2021

---

meetings/2021-05-04.md

doc: add miniutes for meeting 4 May 2021

---

meetings/2021-05-18.md

doc: add minutes for meeting 18 May 2021

---

meetings/2021-06-29.md

doc: add minutes for meeting 29 June 2021

---

meetings/2021-07-15.md

doc: add minutes for meeting 15 July 2021

---

meetings/2021-08-26.md

doc: add minutes for meeting 26 Aug 2021

---

meetings/2021-09-30.md

doc: add minutes from meeting 30 Sep 2021

---

meetings/2021-10-12.md

doc: add minutes 12 Oct 2021

---

meetings/2021-10-28.md

doc: add minutes for Oct 28 2021

---

meetings/2021-11-23.md

doc: add minutes for meeting 23 Nov 2021

---

meetings/2021-12-23.md

doc: add minutes for meeting 23 Dec 2021

---

meetings/2022-01-04.md

doc: add minutes for meeting 4 Jan 2022

---

meetings/2022-01-20.md

doc: add minutes for meeting 20 Jan 2022

---

meetings/2022-02-17.md

doc: add minutes for meeting 17 Feb 2022

---

meetings/2022-04-26.md

doc: add minutes for meeting 26 Apr 2022

---

meetings/2022-05-12.md

capture meeting notes for 2022-05-12

---

meetings/2022-05-24.md

doc: add minutes for meeting 24 May 2022

---

meetings/2022-06-21.md

doc: add minutes for 21 June 2022

---

MEMBERS.md

Hello Everyone,
I'm Ayush Anand, I'm wanting to be a member so I can work with all of the interesting works to gain more experience. I'm available to work on any part of this org like documentation, community engagement, and package building. I'd also like to help give any input in any areas that I have experience in according to my GitHub profile.
Thank you all for your amazing work!

Add @Ayushsunny as a member

---

meetings/2022-09-13.md

doc: add minutes for meeting 13 Sep 2022

---

meetings/2023-01-19.md

doc: add minutes for meeting 19 Jan 2023

---

meetings/2023-02-16.md

doc: add minutes for meeting 16 Feb 2023

---

MEMBERS.md

chore: add member (leobalter)

---

MEMBERS.md

I am currently working on getting the statusboard to work with Express again, and I would like to contribute to the statusboard since it is not currently functioning with recent versions of Node.js.

docs: add @bjohansebas

---

MEMBERS.md

👋 hi all!
helping to make [changes](https://github.com/pkgjs/meet/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Actcpip+) in `meet` and was advised I should submit a PR here
happy to help where I can

✨ Update MEMBERS.md
